### ISSUE TITLE
groupmod: invalid group ID 'docker'

### ISSUE THREAD

**Issue by aliceinwire** [GKernelCI/GBuildbot-worker#12]
groupmod: invalid group ID 'docker'
ERROR: Service 'worker' failed to build: The command '/bin/sh -c groupmod -g $DOCKER_GID docker' returned a non-zero code: 3

**Comment by montjoie** [comment]
you need to set DOCKER_GID in docker-compose.yaml
  worker:
    build: 
        context: ./GBuildbot-worker
        args:
          LAVA_SERVER: xxxx
          LAVA_TOKEN: xxxx
          LAVA_USER: xxxx
          DOCKER_GID: 998

**Comment by aliceinwire** [comment]
thanks
